serviceName: python
containerNamePort: python
replicaCount: 1
certManager: letsencrypt-dev
tlsSecretName: nodejs-secret
image: 130228678771.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs:latest
imagePullPolicy: Always
imagePullSecrets: python-registry-aws
containerPort: 5000
services:
  type: NodePort
