serviceName: python
containerNamePort: python
replicaCount: 1
certManager: letsencrypt-dev
tlsSecretName: nodejs-secret
image: 130228678771.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs:latest
imagePullPolicy: Always
imagePullSecrets: regcred
containerPort: 5000
services:
  type: NodePort
app_version: unknow
app_env: master
# env:
  # - name: app_version
  #   value: unknow
  # - name: app_env
  #   value: unknow
