apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  type: {{ .Values.services.type }}
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: TCP
      name: "{{ .Values.containerNamePort }}-port"
      port: 80
      targetPort: {{ default 8080 .Values.containerPort }}
